#!/bin/bash

ln -sf /usr/share/zoneinfo/Europe/Athens /etc/localtime
hwclock --systohc
sed -i '177s/.//' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "KEYMAP=de_CH-latin1" >> /etc/vconsole.conf
echo "arch" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 arch.localdomain arch" >> /etc/hosts
echo root:password | chpasswd

pacman -S grub efibootmgr networkmanager base-devel linux-tkg-muqss-headers pipewire firewalld flatpak nvidia-dkms nvidia-utils nvidia-settings

grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager
systemctl enable fstrim.timer
systemctl enable firewalld

useradd -m renos
echo renos:password | chpasswd

echo "renos ALL=(ALL) ALL" >> /etc/sudoers.d/renos


printf "\e[1;32mDone! Type exit, umount -a and reboot.\e[0m"






